const { StatusCodes } = require("http-status-codes");
const { Sale, SalesItem, Product } = require("../models/index");

const createSale = async (req, res) => {
  const { items, cashGiven } = req.body;

  if (!items || items.length === 0) {
    return res.status(StatusCodes.NOT_FOUND).json({ msg: "Cart is empty" });
  }

  let totalAmount = 0;

  try {
    const sale = await Sale.create({
      createdBy: req.user.userId,
      totalAmount: 0,
      paymentMethod: "CASH",
    });

    const saleItemsData = [];

    for (const item of items) {
      const product = await Product.findByPk(item.productId);

      if (!product) {
        return res
          .status(StatusCodes.NOT_FOUND)
          .json({ msg: "Product not found" });
      }

      if (product.quantity < item.quantity) {
        return res.status(StatusCodes.BAD_REQUEST).json({
          msg: `Not enough stock for ${product.name}`,
        });
      }

      const itemTotal = product.price * item.quantity;
      totalAmount += itemTotal;

      // Reduce stock
      product.quantity -= item.quantity;
      await product.save();

      saleItemsData.push({
        saleId: sale.id,
        productId: product.id,
        quantity: item.quantity,
        price: product.price,
      });
    }

    // 💰 Payment logic
    if (cashGiven < totalAmount) {
      return res
        .status(StatusCodes.BAD_REQUEST)
        .json({ msg: "Insufficient cash provided" });
    }

    const change = cashGiven - totalAmount;

    // Save sale items
    await SalesItem.bulkCreate(saleItemsData);

    // Update sale
    sale.totalAmount = totalAmount;
    sale.cashGiven = cashGiven;
    sale.change = change;

    await sale.save();

    res.status(StatusCodes.CREATED).json({
      msg: "Sale successful",
      totalAmount,
      cashGiven,
      change,
    });
  } catch (error) {
    res
      .status(StatusCodes.INTERNAL_SERVER_ERROR)
      .json({ error: error.message });
  }
};

const getAllSales = async (req, res) => {
  try {
    const sales = await Sale.findAll({
      include: [
        {
          model: SalesItem,
          include: [Product],
        },
      ],
    });

    const totalSales = await Sale.count();

    const totalRevenue = sales.reduce((acc, sale) => acc + sale.totalAmount, 0);

    res.status(StatusCodes.OK).json({ totalSales, totalRevenue, sales });
  } catch (error) {
    res
      .status(StatusCodes.INTERNAL_SERVER_ERROR)
      .json({ error: error.message });
  }
};

const getAllSalesMade = async (req, res) => {
  try {
    // Get the cashier's user ID from the request (assuming middleware sets req.user)
    const cashierId = req.user.userId;

    // Fetch only sales made by this cashier
    const sales = await Sale.findAll({
      where: { createdBy: cashierId }, // filter by cashier
      include: [
        {
          model: SalesItem,
          include: [Product],
        },
      ],
    });

    // Count of sales made by this cashier
    const totalSales = await Sale.count({
      where: { createdBy: cashierId },
    });

    // Total revenue generated by this cashier
    const totalRevenue = sales.reduce((acc, sale) => acc + sale.totalAmount, 0);

    res.status(StatusCodes.OK).json({ totalSales, totalRevenue, sales });
  } catch (error) {
    res
      .status(StatusCodes.INTERNAL_SERVER_ERROR)
      .json({ error: error.message });
  }
};

const getSaleById = async (req, res) => {
  const { id } = req.params;

  try {
    const sale = await Sale.findByPk(id, {
      include: [
        {
          model: SalesItem,
          include: [Product],
        },
      ],
    });

    if (!sale) {
      return res.status(StatusCodes.NOT_FOUND).json({ msg: "Sale not found" });
    }

    res.status(StatusCodes.OK).json(sale);
  } catch (error) {
    res
      .status(StatusCodes.INTERNAL_SERVER_ERROR)
      .json({ error: error.message });
  }
};

module.exports = { createSale, getAllSales, getAllSalesMade, getSaleById };
